---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  LOCATION: usw2
  SITE_ID: "3"
  TIMEZONE: Europe/Stockholm
  CLUSTER_NAME: nks-eun1
  CLUSTER_DOMAIN: usw2.rajsingh.info

  # K8s
  CLUSTER_POD_CIDR: 10.2.0.0/16
  CLUSTER_SERVICE_CIDR: 10.12.0.0/16
