---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  LOCATION: use1
  FAILOVER: usw2
  SITE_ID: "1"
  TIMEZONE: America/New_York
  CLUSTER_NAME: eks-use1-2
  CLUSTER_DOMAIN: use1.rajsingh.info

  # K8s
  CLUSTER_POD_CIDR: 10.1.0.0/16
  CLUSTER_SERVICE_CIDR: 10.11.0.0/16
