---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale-examples
resources:
  # - ./ts-sidecar.yaml
  # - ./ts-sidecar-userspace.yaml
  # - ./ts-exit-node.yaml
  - ./rbac.yaml
  - ./ts-sidecar-iperf.yaml
  - ./ts-sidecar-peer-relay.yaml
configMapGenerator:
  - name: tailscale-sidecar-dashboard
    files:
      - dashboard.json
    options:
      annotations:
        grafana_folder: tailscale
      labels:
        grafana_dashboard: "1"