---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  LOCATION: usw2
  FAILOVER: use1
  SITE_ID: "2"
  TIMEZONE: America/New_York
  CLUSTER_NAME: eks-usw2
  CLUSTER_DOMAIN: usw2.rajsingh.info

  # K8s
  CLUSTER_POD_CIDR: 10.2.0.0/16
  CLUSTER_SERVICE_CIDR: 10.12.0.0/16