---
apiVersion: v1
kind: Secret
metadata:
  name: istio-remote-secret-use1-1
  namespace: istio-system
  annotations:
    networking.istio.io/cluster: use1-1
  labels:
    istio/multiCluster: "true"
type: Opaque
stringData:
  use1-1: |
    apiVersion: v1
    clusters:
    - cluster:
        server: https://use1-1-k8s-operator.raj.ts.net
      name: use1-1
    contexts:
    - context:
        cluster: use1-1
        user: tailscale-auth
      name: use1-1
    current-context: use1-1
    kind: Config
    preferences: {}
    users:
    - name: tailscale-auth
      user:
        token: unused
---
apiVersion: v1
kind: Secret
metadata:
  name: istio-remote-secret-use1-2
  namespace: istio-system
  annotations:
    networking.istio.io/cluster: use1-2
  labels:
    istio/multiCluster: "true"
type: Opaque
stringData:
  use1-2: |
    apiVersion: v1
    clusters:
    - cluster:
        server: https://use1-2-k8s-operator.raj.ts.net
      name: use1-2
    contexts:
    - context:
        cluster: use1-2
        user: tailscale-auth
      name: use1-2
    current-context: use1-2
    kind: Config
    preferences: {}
    users:
    - name: tailscale-auth
      user:
        token: unused
